/**
 * Where an Indian company can be based, as a list rather than a free-text box.
 *
 * Free text gave us "Bangalore", "Bengaluru", "bangalore" and "Blr" as four
 * different places, which is fine on a screen and useless the moment anybody
 * asks which cities we write the most business in. A closed list makes the
 * answer countable.
 *
 * Roughly the 250 largest cities and the state capitals, each carrying its
 * state so "Hyderabad" is not ambiguous between Telangana and Sindh, and so a
 * GSTIN's state code can be matched against it. Not exhaustive by design: the
 * list covers where group medical business actually sits, and a company
 * genuinely headquartered outside it is rare enough to be worth a conversation.
 */

export type City = { city: string; state: string };

export const CITIES: City[] = [
  // Metros and the largest urban agglomerations
  { city: 'Mumbai', state: 'Maharashtra' },
  { city: 'Delhi', state: 'Delhi' },
  { city: 'Bengaluru', state: 'Karnataka' },
  { city: 'Hyderabad', state: 'Telangana' },
  { city: 'Chennai', state: 'Tamil Nadu' },
  { city: 'Kolkata', state: 'West Bengal' },
  { city: 'Pune', state: 'Maharashtra' },
  { city: 'Ahmedabad', state: 'Gujarat' },
  { city: 'Surat', state: 'Gujarat' },
  { city: 'Jaipur', state: 'Rajasthan' },
  { city: 'Lucknow', state: 'Uttar Pradesh' },
  { city: 'Kanpur', state: 'Uttar Pradesh' },
  { city: 'Nagpur', state: 'Maharashtra' },
  { city: 'Indore', state: 'Madhya Pradesh' },
  { city: 'Thane', state: 'Maharashtra' },
  { city: 'Bhopal', state: 'Madhya Pradesh' },
  { city: 'Visakhapatnam', state: 'Andhra Pradesh' },
  { city: 'Patna', state: 'Bihar' },
  { city: 'Vadodara', state: 'Gujarat' },
  { city: 'Ghaziabad', state: 'Uttar Pradesh' },
  { city: 'Ludhiana', state: 'Punjab' },
  { city: 'Agra', state: 'Uttar Pradesh' },
  { city: 'Nashik', state: 'Maharashtra' },
  { city: 'Faridabad', state: 'Haryana' },
  { city: 'Meerut', state: 'Uttar Pradesh' },
  { city: 'Rajkot', state: 'Gujarat' },
  { city: 'Varanasi', state: 'Uttar Pradesh' },
  { city: 'Srinagar', state: 'Jammu and Kashmir' },
  { city: 'Aurangabad', state: 'Maharashtra' },
  { city: 'Dhanbad', state: 'Jharkhand' },
  { city: 'Amritsar', state: 'Punjab' },
  { city: 'Navi Mumbai', state: 'Maharashtra' },
  { city: 'Allahabad', state: 'Uttar Pradesh' },
  { city: 'Ranchi', state: 'Jharkhand' },
  { city: 'Howrah', state: 'West Bengal' },
  { city: 'Coimbatore', state: 'Tamil Nadu' },
  { city: 'Jabalpur', state: 'Madhya Pradesh' },
  { city: 'Gwalior', state: 'Madhya Pradesh' },
  { city: 'Vijayawada', state: 'Andhra Pradesh' },
  { city: 'Jodhpur', state: 'Rajasthan' },
  { city: 'Madurai', state: 'Tamil Nadu' },
  { city: 'Raipur', state: 'Chhattisgarh' },
  { city: 'Kota', state: 'Rajasthan' },
  { city: 'Chandigarh', state: 'Chandigarh' },
  { city: 'Guwahati', state: 'Assam' },
  { city: 'Solapur', state: 'Maharashtra' },
  { city: 'Hubli-Dharwad', state: 'Karnataka' },
  { city: 'Mysuru', state: 'Karnataka' },
  { city: 'Tiruchirappalli', state: 'Tamil Nadu' },
  { city: 'Bareilly', state: 'Uttar Pradesh' },
  { city: 'Aligarh', state: 'Uttar Pradesh' },
  { city: 'Tiruppur', state: 'Tamil Nadu' },
  { city: 'Moradabad', state: 'Uttar Pradesh' },
  { city: 'Jalandhar', state: 'Punjab' },
  { city: 'Bhubaneswar', state: 'Odisha' },
  { city: 'Salem', state: 'Tamil Nadu' },
  { city: 'Warangal', state: 'Telangana' },
  { city: 'Guntur', state: 'Andhra Pradesh' },
  { city: 'Bhiwandi', state: 'Maharashtra' },
  { city: 'Saharanpur', state: 'Uttar Pradesh' },
  { city: 'Gorakhpur', state: 'Uttar Pradesh' },
  { city: 'Bikaner', state: 'Rajasthan' },
  { city: 'Amravati', state: 'Maharashtra' },
  { city: 'Noida', state: 'Uttar Pradesh' },
  { city: 'Jamshedpur', state: 'Jharkhand' },
  { city: 'Bhilai', state: 'Chhattisgarh' },
  { city: 'Cuttack', state: 'Odisha' },
  { city: 'Firozabad', state: 'Uttar Pradesh' },
  { city: 'Kochi', state: 'Kerala' },
  { city: 'Dehradun', state: 'Uttarakhand' },
  { city: 'Durgapur', state: 'West Bengal' },
  { city: 'Asansol', state: 'West Bengal' },
  { city: 'Nanded', state: 'Maharashtra' },
  { city: 'Kolhapur', state: 'Maharashtra' },
  { city: 'Ajmer', state: 'Rajasthan' },
  { city: 'Gulbarga', state: 'Karnataka' },
  { city: 'Jamnagar', state: 'Gujarat' },
  { city: 'Ujjain', state: 'Madhya Pradesh' },
  { city: 'Loni', state: 'Uttar Pradesh' },
  { city: 'Siliguri', state: 'West Bengal' },
  { city: 'Jhansi', state: 'Uttar Pradesh' },
  { city: 'Ulhasnagar', state: 'Maharashtra' },
  { city: 'Nellore', state: 'Andhra Pradesh' },
  { city: 'Jammu', state: 'Jammu and Kashmir' },
  { city: 'Sangli', state: 'Maharashtra' },
  { city: 'Belgaum', state: 'Karnataka' },
  { city: 'Mangaluru', state: 'Karnataka' },
  { city: 'Ambattur', state: 'Tamil Nadu' },
  { city: 'Tirunelveli', state: 'Tamil Nadu' },
  { city: 'Malegaon', state: 'Maharashtra' },
  { city: 'Gaya', state: 'Bihar' },
  { city: 'Jalgaon', state: 'Maharashtra' },
  { city: 'Udaipur', state: 'Rajasthan' },
  { city: 'Maheshtala', state: 'West Bengal' },
  { city: 'Davanagere', state: 'Karnataka' },
  { city: 'Kozhikode', state: 'Kerala' },
  { city: 'Kurnool', state: 'Andhra Pradesh' },
  { city: 'Rajpur Sonarpur', state: 'West Bengal' },
  { city: 'Bokaro', state: 'Jharkhand' },
  { city: 'South Dumdum', state: 'West Bengal' },
  { city: 'Bellary', state: 'Karnataka' },
  { city: 'Patiala', state: 'Punjab' },
  { city: 'Gopalpur', state: 'West Bengal' },
  { city: 'Agartala', state: 'Tripura' },
  { city: 'Bhagalpur', state: 'Bihar' },
  { city: 'Muzaffarnagar', state: 'Uttar Pradesh' },
  { city: 'Bhatpara', state: 'West Bengal' },
  { city: 'Panihati', state: 'West Bengal' },
  { city: 'Latur', state: 'Maharashtra' },
  { city: 'Dhule', state: 'Maharashtra' },
  { city: 'Rohtak', state: 'Haryana' },
  { city: 'Korba', state: 'Chhattisgarh' },
  { city: 'Bhilwara', state: 'Rajasthan' },
  { city: 'Berhampur', state: 'Odisha' },
  { city: 'Muzaffarpur', state: 'Bihar' },
  { city: 'Ahmednagar', state: 'Maharashtra' },
  { city: 'Mathura', state: 'Uttar Pradesh' },
  { city: 'Kollam', state: 'Kerala' },
  { city: 'Avadi', state: 'Tamil Nadu' },
  { city: 'Kadapa', state: 'Andhra Pradesh' },
  { city: 'Kamarhati', state: 'West Bengal' },
  { city: 'Sambalpur', state: 'Odisha' },
  { city: 'Bilaspur', state: 'Chhattisgarh' },
  { city: 'Shahjahanpur', state: 'Uttar Pradesh' },
  { city: 'Satara', state: 'Maharashtra' },
  { city: 'Bijapur', state: 'Karnataka' },
  { city: 'Rampur', state: 'Uttar Pradesh' },
  { city: 'Shivamogga', state: 'Karnataka' },
  { city: 'Chandrapur', state: 'Maharashtra' },
  { city: 'Junagadh', state: 'Gujarat' },
  { city: 'Thrissur', state: 'Kerala' },
  { city: 'Alwar', state: 'Rajasthan' },
  { city: 'Bardhaman', state: 'West Bengal' },
  { city: 'Kulti', state: 'West Bengal' },
  { city: 'Nizamabad', state: 'Telangana' },
  { city: 'Parbhani', state: 'Maharashtra' },
  { city: 'Tumkur', state: 'Karnataka' },
  { city: 'Khammam', state: 'Telangana' },
  { city: 'Ozhukarai', state: 'Puducherry' },
  { city: 'Bihar Sharif', state: 'Bihar' },
  { city: 'Panipat', state: 'Haryana' },
  { city: 'Darbhanga', state: 'Bihar' },
  { city: 'Bally', state: 'West Bengal' },
  { city: 'Aizawl', state: 'Mizoram' },
  { city: 'Dewas', state: 'Madhya Pradesh' },
  { city: 'Ichalkaranji', state: 'Maharashtra' },
  { city: 'Karnal', state: 'Haryana' },
  { city: 'Bathinda', state: 'Punjab' },
  { city: 'Jalna', state: 'Maharashtra' },
  { city: 'Eluru', state: 'Andhra Pradesh' },
  { city: 'Barasat', state: 'West Bengal' },
  { city: 'Kirari Suleman Nagar', state: 'Delhi' },
  { city: 'Purnia', state: 'Bihar' },
  { city: 'Satna', state: 'Madhya Pradesh' },
  { city: 'Mau', state: 'Uttar Pradesh' },
  { city: 'Sonipat', state: 'Haryana' },
  { city: 'Farrukhabad', state: 'Uttar Pradesh' },
  { city: 'Sagar', state: 'Madhya Pradesh' },
  { city: 'Rourkela', state: 'Odisha' },
  { city: 'Durg', state: 'Chhattisgarh' },
  { city: 'Imphal', state: 'Manipur' },
  { city: 'Ratlam', state: 'Madhya Pradesh' },
  { city: 'Hapur', state: 'Uttar Pradesh' },
  { city: 'Arrah', state: 'Bihar' },
  { city: 'Karimnagar', state: 'Telangana' },
  { city: 'Anantapur', state: 'Andhra Pradesh' },
  { city: 'Etawah', state: 'Uttar Pradesh' },
  { city: 'Ambernath', state: 'Maharashtra' },
  { city: 'North Dumdum', state: 'West Bengal' },
  { city: 'Bharatpur', state: 'Rajasthan' },
  { city: 'Begusarai', state: 'Bihar' },
  { city: 'New Delhi', state: 'Delhi' },
  { city: 'Gandhidham', state: 'Gujarat' },
  { city: 'Baranagar', state: 'West Bengal' },
  { city: 'Tiruvottiyur', state: 'Tamil Nadu' },
  { city: 'Puducherry', state: 'Puducherry' },
  { city: 'Sikar', state: 'Rajasthan' },
  { city: 'Thoothukkudi', state: 'Tamil Nadu' },
  { city: 'Rewa', state: 'Madhya Pradesh' },
  { city: 'Mirzapur', state: 'Uttar Pradesh' },
  { city: 'Raichur', state: 'Karnataka' },
  { city: 'Pali', state: 'Rajasthan' },
  { city: 'Ramagundam', state: 'Telangana' },
  { city: 'Haridwar', state: 'Uttarakhand' },
  { city: 'Vijayanagaram', state: 'Andhra Pradesh' },
  { city: 'Katihar', state: 'Bihar' },
  { city: 'Nagercoil', state: 'Tamil Nadu' },
  { city: 'Sri Ganganagar', state: 'Rajasthan' },
  { city: 'Karawal Nagar', state: 'Delhi' },
  { city: 'Mango', state: 'Jharkhand' },
  { city: 'Thanjavur', state: 'Tamil Nadu' },
  { city: 'Bulandshahr', state: 'Uttar Pradesh' },
  { city: 'Uluberia', state: 'West Bengal' },
  { city: 'Murwara', state: 'Madhya Pradesh' },
  { city: 'Sambhal', state: 'Uttar Pradesh' },
  { city: 'Singrauli', state: 'Madhya Pradesh' },
  { city: 'Nadiad', state: 'Gujarat' },
  { city: 'Secunderabad', state: 'Telangana' },
  { city: 'Naihati', state: 'West Bengal' },
  { city: 'Yamunanagar', state: 'Haryana' },
  { city: 'Bidhan Nagar', state: 'West Bengal' },
  { city: 'Pallavaram', state: 'Tamil Nadu' },
  { city: 'Bidar', state: 'Karnataka' },
  { city: 'Munger', state: 'Bihar' },
  { city: 'Panchkula', state: 'Haryana' },
  { city: 'Burhanpur', state: 'Madhya Pradesh' },
  { city: 'Raurkela', state: 'Odisha' },
  { city: 'Kharagpur', state: 'West Bengal' },
  { city: 'Dindigul', state: 'Tamil Nadu' },
  { city: 'Gandhinagar', state: 'Gujarat' },
  { city: 'Hospet', state: 'Karnataka' },
  { city: 'Nangloi Jat', state: 'Delhi' },
  { city: 'Malda', state: 'West Bengal' },
  { city: 'Ongole', state: 'Andhra Pradesh' },
  { city: 'Deoghar', state: 'Jharkhand' },
  { city: 'Chapra', state: 'Bihar' },
  { city: 'Haldia', state: 'West Bengal' },
  { city: 'Khandwa', state: 'Madhya Pradesh' },
  { city: 'Nandyal', state: 'Andhra Pradesh' },
  { city: 'Chittoor', state: 'Andhra Pradesh' },
  { city: 'Morena', state: 'Madhya Pradesh' },
  { city: 'Amroha', state: 'Uttar Pradesh' },
  { city: 'Anand', state: 'Gujarat' },
  { city: 'Bhind', state: 'Madhya Pradesh' },
  { city: 'Bhalswa Jahangir Pur', state: 'Delhi' },
  { city: 'Madhyamgram', state: 'West Bengal' },
  { city: 'Bhiwani', state: 'Haryana' },
  { city: 'Berhampore', state: 'West Bengal' },
  { city: 'Ambala', state: 'Haryana' },
  { city: 'Morbi', state: 'Gujarat' },
  { city: 'Fatehpur', state: 'Uttar Pradesh' },
  { city: 'Raebareli', state: 'Uttar Pradesh' },
  { city: 'Mahesana', state: 'Gujarat' },
  { city: 'Bharuch', state: 'Gujarat' },
  { city: 'Vapi', state: 'Gujarat' },
  { city: 'Silvassa', state: 'Dadra and Nagar Haveli and Daman and Diu' },
  { city: 'Panaji', state: 'Goa' },
  { city: 'Margao', state: 'Goa' },
  { city: 'Vasco da Gama', state: 'Goa' },
  { city: 'Shimla', state: 'Himachal Pradesh' },
  { city: 'Baddi', state: 'Himachal Pradesh' },
  { city: 'Mohali', state: 'Punjab' },
  { city: 'Gurugram', state: 'Haryana' },
  { city: 'Manesar', state: 'Haryana' },
  { city: 'Greater Noida', state: 'Uttar Pradesh' },
  { city: 'Thiruvananthapuram', state: 'Kerala' },
  { city: 'Kannur', state: 'Kerala' },
  { city: 'Alappuzha', state: 'Kerala' },
  { city: 'Kottayam', state: 'Kerala' },
  { city: 'Palakkad', state: 'Kerala' },
  { city: 'Erode', state: 'Tamil Nadu' },
  { city: 'Vellore', state: 'Tamil Nadu' },
  { city: 'Hosur', state: 'Tamil Nadu' },
  { city: 'Sriperumbudur', state: 'Tamil Nadu' },
  { city: 'Tirupati', state: 'Andhra Pradesh' },
  { city: 'Rajahmundry', state: 'Andhra Pradesh' },
  { city: 'Kakinada', state: 'Andhra Pradesh' },
  { city: 'Amaravati', state: 'Andhra Pradesh' },
  { city: 'Shillong', state: 'Meghalaya' },
  { city: 'Itanagar', state: 'Arunachal Pradesh' },
  { city: 'Kohima', state: 'Nagaland' },
  { city: 'Dimapur', state: 'Nagaland' },
  { city: 'Gangtok', state: 'Sikkim' },
  { city: 'Dibrugarh', state: 'Assam' },
  { city: 'Silchar', state: 'Assam' },
  { city: 'Jorhat', state: 'Assam' },
  { city: 'Bhavnagar', state: 'Gujarat' },
  { city: 'Roorkee', state: 'Uttarakhand' },
  { city: 'Haldwani', state: 'Uttarakhand' },
  { city: 'Rudrapur', state: 'Uttarakhand' },
  { city: 'Port Blair', state: 'Andaman and Nicobar Islands' },
  { city: 'Kavaratti', state: 'Lakshadweep' },
  { city: 'Leh', state: 'Ladakh' },
];

/** "Pune, Maharashtra" — how a location is stored and shown. */
export function cityLabel(entry: City): string {
  return `${entry.city}, ${entry.state}`;
}

export const CITY_LABELS: string[] = CITIES.map(cityLabel);

/**
 * Cities matching what has been typed so far, best first.
 *
 * A prefix match on the city name ranks above one on the state, so typing
 * "man" offers Manesar and Mangaluru before every city in Manipur.
 */
export function searchCities(query: string, limit = 8): string[] {
  const q = query.trim().toLowerCase();
  if (q.length < 2) return [];

  const starts: string[] = [];
  const contains: string[] = [];

  for (const entry of CITIES) {
    const city = entry.city.toLowerCase();
    if (city.startsWith(q)) starts.push(cityLabel(entry));
    else if (city.includes(q) || entry.state.toLowerCase().startsWith(q)) {
      contains.push(cityLabel(entry));
    }
    if (starts.length >= limit) break;
  }

  return [...starts, ...contains].slice(0, limit);
}
